from scipy import constants

print(constants.liter)
print(constants.pi)
print(constants.giga)
print(constants.mega)
print(constants.kilo)
print(constants.hecto)
print(constants.deka)
print(constants.deci)
print(constants.centi)
print(constants.milli)
print(constants.micro)
print(constants.nano)
print(constants.gram)
print(constants.lb)
print(constants.pound)
print(constants.degree)
print(constants.minute)
print(constants.hour)
print(constants.day)
print(constants.week)
print(constants.year)
print(constants.inch)
print(constants.foot)
print(constants.yard)
print(constants.mile)
print(constants.mil)
print(constants.hectare)
print(constants.acre)
print(constants.liter)
print(constants.litre)
print(constants.gallon)
print(constants.hp)
print(constants.horsepower)

